
import re
st = input("Enter a String : ")
res = re.findall(r".",st)
print(res)
print(len(res))
print("------------------")
res = re.findall(r"\w",st)
print(res)
print(len(res))
print("------------------")
res = re.findall(r"\w*",st)
print(res)
print(len(res))
print("------------------")
res = re.findall(r"\w+",st)
print(res)
print(len(res))
print("------------------")
res = re.findall(r"^\w+",st)
print(res)
print(len(res))
print("------------------")
res = re.findall(r"\w+$",st)
print(res)
print(len(res))